[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "https://developersdomain.netlify.app/"
  to = "https://www.aviatecoders.com/"
  status = 301
  force = true
